"""
Django settings for tmdb project.

Generated by 'django-admin startproject' using Django 2.1.7., but then i
removed a bunch of stock settings because we don't need them all for this project.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '328va0h1f$&kxhh678d7z!0ky^i^@9a%spv7ut#w1#13@g3mx+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition
INSTALLED_APPS = [
    'django.contrib.staticfiles',

    # billy's app
    'movies',
]


ROOT_URLCONF = 'tmdb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# settings used by my movie app, needed to access TMDB's API
# https://www.themoviedb.org/documentation/api?language=en
TMDB_API_BASE_URL = 'https://api.themoviedb.org/3/'
TMDB_API_KEY = '9b609a05717d5c7e8a0641de59420317'
